/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package logic.Presentacion;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import logic.Fabrica;
import logic.Institucion.InstitucionDeportiva;
import logic.Institucion.ManejadorInstitucion;
import logic.Institucion.controllers.IControllerModificarInstitucion;
import logic.Usuario.ManejadorUsuarios;
import logic.Usuario.Usuario;
import logic.Usuario.controllers.IControllerModificarUsuario;

/**
 *
 * @author Admin
 */
public class ModificarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarUsuario
     */
    public ModificarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMUusuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextoNombreMU = new javax.swing.JLabel();
        jTextFieldMUnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMUapellido = new javax.swing.JTextField();
        TextoMUFnacimiento = new javax.swing.JLabel();
        jDateChooserMUFnacimiento = new com.toedter.calendar.JDateChooser();
        jButtonMUA = new javax.swing.JButton();
        jButtonMUC = new javax.swing.JButton();
        jButtonMUS = new javax.swing.JButton();

        setTitle("Modificar Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jComboBoxMUusuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMUusuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxMUusuariosFocusGained(evt);
            }
        });

        jLabel1.setText("Usuarios:");

        TextoNombreMU.setText("Nombre:");

        jLabel2.setText("Apellido:");

        TextoMUFnacimiento.setText("Fecha de Nacimiento:");

        jButtonMUA.setText("Aceptar");
        jButtonMUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMUAActionPerformed(evt);
            }
        });

        jButtonMUC.setText("Cancelar");
        jButtonMUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMUCActionPerformed(evt);
            }
        });

        jButtonMUS.setText("Seleccionar");
        jButtonMUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonMUA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonMUC)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoNombreMU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoMUFnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMUS)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxMUusuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMUnombre)
                        .addComponent(jTextFieldMUapellido)
                        .addComponent(jDateChooserMUFnacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxMUusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonMUS)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoNombreMU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMUnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMUapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoMUFnacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserMUFnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMUA)
                    .addComponent(jButtonMUC))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//controllerUsuario.modificarUsuario(nickname, nuevoNombre, nuevoApellido, nuevafecha);
    private void jComboBoxMUusuariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxMUusuariosFocusGained
            
    }//GEN-LAST:event_jComboBoxMUusuariosFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
            addUsuariosToComboBox();
            jTextFieldMUnombre.setEnabled(false);
            jTextFieldMUapellido.setEnabled(false);
            jDateChooserMUFnacimiento.setEnabled(false);

    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonMUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMUSActionPerformed
        String usuario = jComboBoxMUusuarios.getSelectedItem().toString();
        Usuario user = ManejadorUsuarios.getUser(usuario);
        jTextFieldMUnombre.setText(user.getNombre());
        jTextFieldMUapellido.setText(user.getApellido());
        //jDateChooserMUFnacimiento.setDateFormatString(user.getFechaNacFromatted());
        
        jTextFieldMUnombre.setEnabled(true);
        jTextFieldMUapellido.setEnabled(true);
        jDateChooserMUFnacimiento.setEnabled(true);
    }//GEN-LAST:event_jButtonMUSActionPerformed

    private void jButtonMUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMUCActionPerformed
        jTextFieldMUnombre.setText("");
        jTextFieldMUapellido.setText("");
        this.dispose();
    }//GEN-LAST:event_jButtonMUCActionPerformed

    private void jButtonMUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMUAActionPerformed
        Fabrica factory = new Fabrica();
        String usuario = jComboBoxMUusuarios.getSelectedItem().toString();
        IControllerModificarUsuario controller = factory.getControllerModificarUsuario();

        String nuevonombre = jTextFieldMUnombre.getText();
        String nuevoapellido = jTextFieldMUapellido.getText();
        
        Date selectedDate = jDateChooserMUFnacimiento.getDate();
        LocalDate nuevafecha = selectedDate.toInstant().atZone(jDateChooserMUFnacimiento.getCalendar().getTimeZone().toZoneId()).toLocalDate();

        
        controller.modificarUsuario(usuario, nuevonombre, nuevoapellido, nuevafecha);
        jTextFieldMUnombre.setText("");
        jTextFieldMUapellido.setText("");
    }//GEN-LAST:event_jButtonMUAActionPerformed

    private void addUsuariosToComboBox(){
        List<Usuario> usuarios = ManejadorUsuarios.getUsuarios();

        jComboBoxMUusuarios.removeAllItems();

        for (Usuario usuario : usuarios) {
            jComboBoxMUusuarios.addItem(usuario.getNickname());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoMUFnacimiento;
    private javax.swing.JLabel TextoNombreMU;
    private javax.swing.JButton jButtonMUA;
    private javax.swing.JButton jButtonMUC;
    private javax.swing.JButton jButtonMUS;
    private javax.swing.JComboBox<String> jComboBoxMUusuarios;
    private com.toedter.calendar.JDateChooser jDateChooserMUFnacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldMUapellido;
    private javax.swing.JTextField jTextFieldMUnombre;
    // End of variables declaration//GEN-END:variables
}
