/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package logic.Presentacion;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logic.Fabrica;
import logic.Usuario.controllers.IControllerAltaUsuario;
import logic.Institucion.InstitucionDeportiva;
import logic.Institucion.ManejadorInstitucion;

/**
 *
 * @author xSanPrax
 */
public class RegistrarUsuarioCU extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarUsuarioCU
     */
    private String imagenBase64;
    public RegistrarUsuarioCU() {
        initComponents();
        jTextFieldDescProf.setEnabled(false);
        jTextFieldBioProf.setEnabled(false);
        jTextFieldWebProf.setEnabled(false);
        jComboBoxRUInstitucion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jCheckBoxPROF = new javax.swing.JCheckBox();
        TextoInstiPROF = new javax.swing.JLabel();
        jTextFieldApellidoU = new javax.swing.JTextField();
        jComboBoxRUInstitucion = new javax.swing.JComboBox<>();
        jButtonRUC = new javax.swing.JButton();
        jTextFieldNicknameU = new javax.swing.JTextField();
        TextoNombreU = new javax.swing.JLabel();
        jTextFieldEmailU = new javax.swing.JTextField();
        TextoApellidoU = new javax.swing.JLabel();
        TextoNicknameU = new javax.swing.JLabel();
        jDateChooserFNU = new com.toedter.calendar.JDateChooser();
        jTextFieldDescProf = new javax.swing.JTextField();
        TextoBioProf = new javax.swing.JLabel();
        jTextFieldBioProf = new javax.swing.JTextField();
        TextoWebProf = new javax.swing.JLabel();
        jTextFieldWebProf = new javax.swing.JTextField();
        TextoEmailU = new javax.swing.JLabel();
        TextoFNU = new javax.swing.JLabel();
        TextoIngresedatosU = new javax.swing.JLabel();
        jTextFieldNombreU = new javax.swing.JTextField();
        jButtonRUA = new javax.swing.JButton();
        jComboBoxNombreU = new javax.swing.JComboBox<>();
        jComboBoxApellidoU = new javax.swing.JComboBox<>();
        jComboBoxNicknameU = new javax.swing.JComboBox<>();
        jComboBoxEmailU = new javax.swing.JComboBox<>();
        TextoDescProf = new javax.swing.JLabel();
        jButtonRUM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldContrasena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCContrasena = new javax.swing.JTextField();
        jFileChooserImgUsuario = new javax.swing.JFileChooser();

        setTitle("Registrar Usuario");

        jCheckBoxPROF.setText("Profesor?");
        jCheckBoxPROF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPROFActionPerformed(evt);
            }
        });

        TextoInstiPROF.setText("Institucion:");

        jButtonRUC.setText("Cancelar");
        jButtonRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUCActionPerformed(evt);
            }
        });

        TextoNombreU.setText("Nombre:");

        TextoApellidoU.setText("Apellido:");

        TextoNicknameU.setText("Nickname:");

        TextoBioProf.setText("Biografia:");

        TextoWebProf.setText("Sitio web:");

        TextoEmailU.setText("Correo electrónico:");

        TextoFNU.setText("Fecha de nacimiento:");

        TextoIngresedatosU.setText("Ingrese los siguientes datos:");

        jButtonRUA.setText("Aceptar");
        jButtonRUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUAActionPerformed(evt);
            }
        });

        jComboBoxNombreU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreUActionPerformed(evt);
            }
        });

        jComboBoxApellidoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxApellidoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxApellidoUActionPerformed(evt);
            }
        });

        jComboBoxNicknameU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNicknameU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNicknameUActionPerformed(evt);
            }
        });

        jComboBoxEmailU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmailU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmailUActionPerformed(evt);
            }
        });

        TextoDescProf.setText("Descripción:");

        jButtonRUM.setText("Modificar.Clien");
        jButtonRUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUMActionPerformed(evt);
            }
        });

        jLabel1.setText("Contrasena");

        jLabel2.setText("Confirmar Contrasena");

        jFileChooserImgUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserImgUsuarioActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jCheckBoxPROF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoInstiPROF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldApellidoU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxRUInstitucion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRUC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldNicknameU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoNombreU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldEmailU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoApellidoU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoNicknameU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDateChooserFNU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldDescProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoBioProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldBioProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoWebProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldWebProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoEmailU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoFNU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoIngresedatosU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldNombreU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRUA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxNombreU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxApellidoU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxNicknameU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxEmailU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TextoDescProf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRUM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldCContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jFileChooserImgUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextoInstiPROF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellidoU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoNicknameU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoEmailU, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextoFNU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoDescProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoBioProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoWebProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextoNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(149, 149, 149)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxRUInstitucion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldWebProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDateChooserFNU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDescProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFileChooserImgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxPROF)
                        .addGap(82, 82, 82)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jButtonRUA)
                                .addGap(44, 44, 44)
                                .addComponent(jButtonRUC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRUM))
                            .addComponent(TextoIngresedatosU))))
                .addGap(171, 171, 171))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(TextoIngresedatosU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNicknameU, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jComboBoxNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(TextoFNU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextoDescProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jDateChooserFNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDescProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jFileChooserImgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldWebProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextoWebProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoInstiPROF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRUInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jCheckBoxPROF))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRUA)
                            .addComponent(jButtonRUC)
                            .addComponent(jButtonRUM))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        getAccessibleContext().setAccessibleName("RegistrarUsuario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRUMActionPerformed
        ModificarUsuario userm = new ModificarUsuario();
        userm.setSize(800, 650);
        int desktopWidth = jDesktopPane1.getWidth();
        int desktopHeight = jDesktopPane1.getHeight();

        // Calcular coordenadas para centrar el JInternalFrame
        int x = (desktopWidth - userm.getWidth()) / 2;
        int y = (desktopHeight - userm.getHeight()) / 2;
        userm.setLocation(x - 10, y - 20);
        userm.setVisible(true);
        // internalFrame.setSize(300, 200);
        // internalFrame.setVisible(true);
        jDesktopPane1.add(userm);
        userm.toFront();
    }//GEN-LAST:event_jButtonRUMActionPerformed

    private void jFileChooserImgUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserImgUsuarioActionPerformed
          try {
        File selectedFile = jFileChooserImgUsuario.getSelectedFile(); // Obtener el archivo seleccionado

        FileInputStream fis = new FileInputStream(selectedFile);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int bytesRead;
        while ((bytesRead = fis.read(buffer)) != -1) {
            bos.write(buffer, 0, bytesRead);
        }
        imagenBase64 = Base64.getEncoder().encodeToString(bos.toByteArray());

        fis.close();
        bos.close();
        
         JOptionPane.showMessageDialog(this, "Foto seleccionada correctamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) { 
        System.out.println("Error al leer el archivo: " + e.getMessage());
    }
    }//GEN-LAST:event_jFileChooserImgUsuarioActionPerformed



    
    
    private void jButtonRUCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRUCActionPerformed
        jTextFieldNombreU.setText("");
        jTextFieldApellidoU.setText("");
        jTextFieldNicknameU.setText("");
        jTextFieldEmailU.setText("");
        jTextFieldDescProf.setText("");
        jTextFieldBioProf.setText("");
        jTextFieldWebProf.setText("");
        jTextFieldContrasena.setText("");
        jTextFieldCContrasena.setText("");
        this.dispose();
    }// GEN-LAST:event_jButtonRUCActionPerformed

    

    
    private void jButtonRUAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRUAActionPerformed
        
         try {
        Fabrica factory = new Fabrica();
        IControllerAltaUsuario controllerAltaUsuario = factory.getControladorAltaUsuario();

        Date selectedDate = jDateChooserFNU.getDate();
        LocalDate fechaNacimiento = selectedDate.toInstant()
                .atZone(jDateChooserFNU.getCalendar().getTimeZone().toZoneId()).toLocalDate();

        String nickname = jTextFieldNicknameU.getText();
        String nombre = jTextFieldNombreU.getText();
        String apellido = jTextFieldApellidoU.getText();
        String email = jTextFieldEmailU.getText();
        String descripcion = jTextFieldDescProf.getText();
        String biografia = jTextFieldBioProf.getText();
        String sitioweb = jTextFieldWebProf.getText();
        String contrasena = jTextFieldContrasena.getText();
        String ccontrasena = jTextFieldCContrasena.getText();

        // Validar que las contraseñas coincidan
        if (!contrasena.equals(ccontrasena)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si las contraseñas no coinciden
        }

        boolean action;

        // Llamar a tu función pasando la variable como argumento
        if (jCheckBoxPROF.isSelected()) {
            InstitucionDeportiva institucionDeportiva = ManejadorInstitucion
                    .getInstitucionesByName(jComboBoxRUInstitucion.getSelectedItem().toString());

            String imgBase64 = imagenBase64;

            action = controllerAltaUsuario.addProfesor(nickname, nombre, apellido, email, fechaNacimiento,
                    descripcion, biografia, sitioweb, institucionDeportiva, contrasena, imgBase64);
        } else {

            String imgBase64 = imagenBase64;

            action = controllerAltaUsuario.addSocio(nickname, nombre, apellido, email, fechaNacimiento, contrasena, imgBase64);
        }

        if (action) {
            jTextFieldNombreU.setText("");
            jTextFieldApellidoU.setText("");
            jTextFieldNicknameU.setText("");
            jTextFieldEmailU.setText("");
            jTextFieldDescProf.setText("");
            jTextFieldBioProf.setText("");
            jTextFieldWebProf.setText("");
        }

    }catch (NumberFormatException e) {
        // Manejar una excepción si no se puede convertir el texto a un número
        System.out.println("El texto no es un número válido");
    }
        // Manejar una excepción de E/S si ocurre algún problema al leer el archivo
        
    
    }
    




    private void jComboBoxNombreUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxNombreUActionPerformed
        Object selectedItem = jComboBoxNombreU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldNombreU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxNombreUActionPerformed

    private void jComboBoxApellidoUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxApellidoUActionPerformed
        Object selectedItem = jComboBoxApellidoU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldApellidoU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxApellidoUActionPerformed

    private void jComboBoxNicknameUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxNicknameUActionPerformed
        Object selectedItem = jComboBoxNicknameU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldNicknameU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxNicknameUActionPerformed

    private void jComboBoxEmailUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxEmailUActionPerformed
        Object selectedItem = jComboBoxEmailU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldEmailU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxEmailUActionPerformed

    private void addInstitucionesToComboBox(String option) {

        List<InstitucionDeportiva> instituciones = ManejadorInstitucion.getInstituciones();
        // Object selectedItem;

        switch (option) {
            case "Profesor":

                jComboBoxRUInstitucion.removeAllItems();

                for (InstitucionDeportiva institucion : instituciones) {
                    jComboBoxRUInstitucion.addItem(institucion.getNombre());

                }

                break;
            default:
                break;
        }
    }

    private void jCheckBoxPROFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxPROFActionPerformed
        if (jCheckBoxPROF.isSelected()) {
            jTextFieldDescProf.setEnabled(true);
            jTextFieldBioProf.setEnabled(true);
            jTextFieldWebProf.setEnabled(true);
            jComboBoxRUInstitucion.setEnabled(true);
            addInstitucionesToComboBox("Profesor");
        } else {

            jTextFieldDescProf.setEnabled(false);
            jTextFieldBioProf.setEnabled(false);
            jTextFieldWebProf.setEnabled(false);
            jComboBoxRUInstitucion.setEnabled(false);
        }
    }// GEN-LAST:event_jCheckBoxPROFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoApellidoU;
    private javax.swing.JLabel TextoBioProf;
    private javax.swing.JLabel TextoDescProf;
    private javax.swing.JLabel TextoEmailU;
    private javax.swing.JLabel TextoFNU;
    private javax.swing.JLabel TextoIngresedatosU;
    private javax.swing.JLabel TextoInstiPROF;
    private javax.swing.JLabel TextoNicknameU;
    private javax.swing.JLabel TextoNombreU;
    private javax.swing.JLabel TextoWebProf;
    private javax.swing.JButton jButtonRUA;
    private javax.swing.JButton jButtonRUC;
    private javax.swing.JButton jButtonRUM;
    private javax.swing.JCheckBox jCheckBoxPROF;
    private javax.swing.JComboBox<String> jComboBoxApellidoU;
    private javax.swing.JComboBox<String> jComboBoxEmailU;
    private javax.swing.JComboBox<String> jComboBoxNicknameU;
    private javax.swing.JComboBox<String> jComboBoxNombreU;
    private javax.swing.JComboBox<String> jComboBoxRUInstitucion;
    private com.toedter.calendar.JDateChooser jDateChooserFNU;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooserImgUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldApellidoU;
    private javax.swing.JTextField jTextFieldBioProf;
    private javax.swing.JTextField jTextFieldCContrasena;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldDescProf;
    private javax.swing.JTextField jTextFieldEmailU;
    private javax.swing.JTextField jTextFieldNicknameU;
    private javax.swing.JTextField jTextFieldNombreU;
    private javax.swing.JTextField jTextFieldWebProf;
    // End of variables declaration//GEN-END:variables
}
