/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package logic.Presentacion;

import logic.Fabrica;
import logic.Institucion.controllers.ControllerAltaInstitucionDeportiva;
import logic.Institucion.controllers.IControllerAltaInstitucionDeportiva;

/**
 *
 * @author Admin
 */
public class RegistrarInstitucionCU extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarInstitucionCU
     */
    public RegistrarInstitucionCU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptarInt = new javax.swing.JButton();
        jLabelNombreInstitucion = new javax.swing.JLabel();
        jTextFieldNombreInstitucion = new javax.swing.JTextField();
        jLabelDescInstitucion = new javax.swing.JLabel();
        jTextFieldDescInstitucion = new javax.swing.JTextField();
        jLabelurlInstitucion = new javax.swing.JLabel();
        jTextFieldUrl = new javax.swing.JTextField();
        jButtonCancelarInst = new javax.swing.JButton();

        setTitle("Registrar Institucion");

        jButtonAceptarInt.setText("Aceptar");
        jButtonAceptarInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarIntActionPerformed(evt);
            }
        });

        jLabelNombreInstitucion.setText("Nombre Institucion");

        jLabelDescInstitucion.setText("Descripcion");

        jLabelurlInstitucion.setText("URL");

        jButtonCancelarInst.setText("Cancelar");
        jButtonCancelarInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarInstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelarInst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptarInt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreInstitucion)
                    .addComponent(jLabelDescInstitucion)
                    .addComponent(jLabelurlInstitucion))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreInstitucion)
                    .addComponent(jTextFieldNombreInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescInstitucion)
                    .addComponent(jTextFieldDescInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelurlInstitucion)
                    .addComponent(jTextFieldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarInst)
                    .addComponent(jButtonAceptarInt))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarIntActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAceptarIntActionPerformed
        Fabrica factory = new Fabrica();

        IControllerAltaInstitucionDeportiva controller = factory.getControladorAltaInstitucionDeportiva();

        String nombreInstitucion = jTextFieldNombreInstitucion.getText();
        String descrInstitucion = jTextFieldDescInstitucion.getText();
        String urlInstitucion = jTextFieldUrl.getText();
        controller.addInstitucionDeportiva(nombreInstitucion, descrInstitucion, urlInstitucion);
    }// GEN-LAST:event_jButtonAceptarIntActionPerformed

    private void jButtonCancelarInstActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelarInstActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButtonCancelarInstActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarInt;
    private javax.swing.JButton jButtonCancelarInst;
    private javax.swing.JLabel jLabelDescInstitucion;
    private javax.swing.JLabel jLabelNombreInstitucion;
    private javax.swing.JLabel jLabelurlInstitucion;
    private javax.swing.JTextField jTextFieldDescInstitucion;
    private javax.swing.JTextField jTextFieldNombreInstitucion;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables
}
