/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package logic.Presentacion;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import application.Ventana;
import java.time.LocalTime;
import logic.Fabrica;
import logic.ActividadDeportiva.ActividadDeportiva;
import logic.ActividadDeportiva.ManejadorActividad;
import logic.ActividadDeportiva.controllers.IControllerAltaActividad;
import logic.Usuario.ManejadorUsuarios;
import logic.Usuario.Profesor;
import logic.Usuario.Socio;
import logic.Usuario.Usuario;
import logic.Usuario.controllers.IControllerAltaUsuario;
import logic.Usuario.controllers.IControllerConsultaUsuario;
import logic.Clase.Clase;
import logic.Clase.controllers.IControllerAltaClase;
import logic.Institucion.InstitucionDeportiva;
import logic.Institucion.ManejadorInstitucion;
import logic.Presentacion.*;

/**
 *
 * @author Admin
 */
public class RegistrarUsuarioCU extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarUsuarioCU
     */

    public RegistrarUsuarioCU() {
        initComponents();
        jTextFieldDescProf.setEnabled(false);
        jTextFieldBioProf.setEnabled(false);
        jTextFieldWebProf.setEnabled(false);
        jComboBoxRUInstitucion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescProf = new javax.swing.JTextField();
        TextoBioProf = new javax.swing.JLabel();
        jTextFieldBioProf = new javax.swing.JTextField();
        TextoWebProf = new javax.swing.JLabel();
        jTextFieldWebProf = new javax.swing.JTextField();
        jCheckBoxPROF = new javax.swing.JCheckBox();
        TextoInstiPROF = new javax.swing.JLabel();
        jTextFieldApellidoU = new javax.swing.JTextField();
        jComboBoxRUInstitucion = new javax.swing.JComboBox<>();
        jButtonRUC = new javax.swing.JButton();
        jTextFieldNicknameU = new javax.swing.JTextField();
        TextoNombreU = new javax.swing.JLabel();
        jTextFieldEmailU = new javax.swing.JTextField();
        TextoApellidoU = new javax.swing.JLabel();
        TextoNicknameU = new javax.swing.JLabel();
        TextoEmailU = new javax.swing.JLabel();
        TextoFNU = new javax.swing.JLabel();
        TextoIngresedatosU = new javax.swing.JLabel();
        jTextFieldNombreU = new javax.swing.JTextField();
        jButtonRUA = new javax.swing.JButton();
        jComboBoxNombreU = new javax.swing.JComboBox<>();
        jComboBoxApellidoU = new javax.swing.JComboBox<>();
        jComboBoxNicknameU = new javax.swing.JComboBox<>();
        jComboBoxEmailU = new javax.swing.JComboBox<>();
        TextoDescProf = new javax.swing.JLabel();
        jDateChooserFNU = new com.toedter.calendar.JDateChooser();

        setTitle("Registrar Usuario");

        TextoBioProf.setText("Biografia:");

        TextoWebProf.setText("Sitio web:");

        jCheckBoxPROF.setText("Profesor?");
        jCheckBoxPROF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPROFActionPerformed(evt);
            }
        });

        TextoInstiPROF.setText("Institucion:");

        jButtonRUC.setText("Cancelar");
        jButtonRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUCActionPerformed(evt);
            }
        });

        TextoNombreU.setText("Nombre:");

        TextoApellidoU.setText("Apellido:");

        TextoNicknameU.setText("Nickname:");

        TextoEmailU.setText("Correo electrónico:");

        TextoFNU.setText("Fecha de nacimiento:");

        TextoIngresedatosU.setText("Ingrese los siguientes datos:");

        jButtonRUA.setText("Aceptar");
        jButtonRUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUAActionPerformed(evt);
            }
        });

        jComboBoxNombreU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreUActionPerformed(evt);
            }
        });

        jComboBoxApellidoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxApellidoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxApellidoUActionPerformed(evt);
            }
        });

        jComboBoxNicknameU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNicknameU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNicknameUActionPerformed(evt);
            }
        });

        jComboBoxEmailU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmailU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmailUActionPerformed(evt);
            }
        });

        TextoDescProf.setText("Descripción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRUA)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonRUC)
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(TextoIngresedatosU))
                            .addComponent(jCheckBoxPROF)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextoInstiPROF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextoNombreU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoApellidoU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoNicknameU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoEmailU, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoFNU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextoDescProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextoBioProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextoWebProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxRUInstitucion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldWebProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDateChooserFNU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDescProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoIngresedatosU)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoApellidoU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoNicknameU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxNicknameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoEmailU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoFNU)
                        .addGap(18, 18, 18)
                        .addComponent(TextoDescProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooserFNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldDescProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBioProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldWebProf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextoWebProf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoInstiPROF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRUInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jCheckBoxPROF)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRUA)
                    .addComponent(jButtonRUC))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("RegistrarUsuario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRUCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRUCActionPerformed
        jTextFieldNombreU.setText("");
        jTextFieldApellidoU.setText("");
        jTextFieldNicknameU.setText("");
        jTextFieldEmailU.setText("");
        jTextFieldDescProf.setText("");
        jTextFieldBioProf.setText("");
        jTextFieldWebProf.setText("");
        this.dispose();
    }// GEN-LAST:event_jButtonRUCActionPerformed

    private void jButtonRUAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRUAActionPerformed
        try {
            Fabrica factory = new Fabrica();

            IControllerAltaUsuario controllerAltaUsuario = factory.getControladorAltaUsuario();

            
            Date selectedDate = jDateChooserFNU.getDate();
            LocalDate fechaNacimiento = selectedDate.toInstant()
                    .atZone(jDateChooserFNU.getCalendar().getTimeZone().toZoneId()).toLocalDate();

            String nickname = jTextFieldNicknameU.getText();
            String nombre = jTextFieldNombreU.getText();
            String apellido = jTextFieldApellidoU.getText();
            String email = jTextFieldEmailU.getText();
            String descripcion = jTextFieldDescProf.getText();
            String biografia = jTextFieldBioProf.getText();
            String sitioweb = jTextFieldWebProf.getText();
            boolean action;
            // Llamar a tu función pasando la variable como argumento

            InstitucionDeportiva institucionDeportiva = ManejadorInstitucion
                    .getInstitucionesByName(jComboBoxRUInstitucion.getSelectedItem().toString());

            if (jCheckBoxPROF.isSelected()) {
                action = controllerAltaUsuario.addProfesor(nickname, nombre, apellido, email,
                        fechaNacimiento,
                        descripcion,
                        biografia, sitioweb, institucionDeportiva);
            } else {
                action = controllerAltaUsuario.addSocio(nickname, nombre, apellido, email,
                        fechaNacimiento);
            }

            if (action) {
                jTextFieldNombreU.setText("");
                jTextFieldApellidoU.setText("");
                jTextFieldNicknameU.setText("");
                jTextFieldEmailU.setText("");
                jTextFieldDescProf.setText("");
                jTextFieldBioProf.setText("");
                jTextFieldWebProf.setText("");
            }

        } catch (NumberFormatException e) {
            // Manejar una excepción si no se puede convertir el texto a un número
            System.out.println("El texto no es un número válido");
        }
    }// GEN-LAST:event_jButtonRUAActionPerformed

    private void jComboBoxNombreUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxNombreUActionPerformed
        Object selectedItem = jComboBoxNombreU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldNombreU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxNombreUActionPerformed

    private void jComboBoxApellidoUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxApellidoUActionPerformed
        Object selectedItem = jComboBoxApellidoU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldApellidoU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxApellidoUActionPerformed

    private void jComboBoxNicknameUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxNicknameUActionPerformed
        Object selectedItem = jComboBoxNicknameU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldNicknameU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxNicknameUActionPerformed

    private void jComboBoxEmailUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxEmailUActionPerformed
        Object selectedItem = jComboBoxEmailU.getSelectedItem();

        // Realizar acciones basadas en el elemento seleccionado
        if (selectedItem != null) {
            String selectedText = selectedItem.toString(); // Convertir el elemento a String
            jTextFieldEmailU.setText(selectedText); // Establecer el texto en el JTextField
        }
    }// GEN-LAST:event_jComboBoxEmailUActionPerformed

    private void addInstitucionesToComboBox(String option) {

        List<InstitucionDeportiva> instituciones = ManejadorInstitucion.getInstituciones();
        // Object selectedItem;

        switch (option) {
            case "Profesor":

                jComboBoxRUInstitucion.removeAllItems();

                for (InstitucionDeportiva institucion : instituciones) {
                    jComboBoxRUInstitucion.addItem(institucion.getNombre());

                }

                break;
            default:
                break;
        }
    }

    private void jCheckBoxPROFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBoxPROFActionPerformed
        if (jCheckBoxPROF.isSelected()) {
            jTextFieldDescProf.setEnabled(true);
            jTextFieldBioProf.setEnabled(true);
            jTextFieldWebProf.setEnabled(true);
            jComboBoxRUInstitucion.setEnabled(true);
            addInstitucionesToComboBox("Profesor");
        } else {

            jTextFieldDescProf.setEnabled(false);
            jTextFieldBioProf.setEnabled(false);
            jTextFieldWebProf.setEnabled(false);
            jComboBoxRUInstitucion.setEnabled(false);
        }
    }// GEN-LAST:event_jCheckBoxPROFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoApellidoU;
    private javax.swing.JLabel TextoBioProf;
    private javax.swing.JLabel TextoDescProf;
    private javax.swing.JLabel TextoEmailU;
    private javax.swing.JLabel TextoFNU;
    private javax.swing.JLabel TextoIngresedatosU;
    private javax.swing.JLabel TextoInstiPROF;
    private javax.swing.JLabel TextoNicknameU;
    private javax.swing.JLabel TextoNombreU;
    private javax.swing.JLabel TextoWebProf;
    private javax.swing.JButton jButtonRUA;
    private javax.swing.JButton jButtonRUC;
    private javax.swing.JCheckBox jCheckBoxPROF;
    private javax.swing.JComboBox<String> jComboBoxApellidoU;
    private javax.swing.JComboBox<String> jComboBoxEmailU;
    private javax.swing.JComboBox<String> jComboBoxNicknameU;
    private javax.swing.JComboBox<String> jComboBoxNombreU;
    private javax.swing.JComboBox<String> jComboBoxRUInstitucion;
    private com.toedter.calendar.JDateChooser jDateChooserFNU;
    private javax.swing.JTextField jTextFieldApellidoU;
    private javax.swing.JTextField jTextFieldBioProf;
    private javax.swing.JTextField jTextFieldDescProf;
    private javax.swing.JTextField jTextFieldEmailU;
    private javax.swing.JTextField jTextFieldNicknameU;
    private javax.swing.JTextField jTextFieldNombreU;
    private javax.swing.JTextField jTextFieldWebProf;
    // End of variables declaration//GEN-END:variables
}
